name: message-workflow
run-name: ${{github.actor}} is running the message-workflow
on:
  push:
    branches: ["master"]
  workflow_dispatch:
  workflow_call:
    outputs:
      message:
        description: "Output Message"
        value: ${{ jobs.list_job.outputs.message }}
      data:
        description: "Output Data"
        value: ${{ jobs.list_job.outputs.data }}
env:
  FOR: myself
  STACK: "ga,wp,es,pr,ja,js,py,sh"

jobs:
  list_job:
    outputs:
      message: ${{ steps.my_step.outputs.message }}
      data: ${{ steps.my_step.outputs.data }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14]
    steps:
      - name: node-version-checker
        run: node --version
      - name: my-step-one
        id: my_step
        if: ${{ env.FOR == 'myself' }}
        run: |
          echo "This is for you"
          echo "message=${{ env.STACK }}" >> $GITHUB_OUTPUT
      - name: step-one
        id: step_one
        if: ${{ !cancelled() && env.FOR != 'myself' }}
        run: |
          echo "Impossible"
