name: prettier-workflow
run-name: ${{ github.actor }} is running the prettier workflow
on:
  push:
    branches: ["master"]
  workflow_dispatch:
  workflow_call:
jobs:
  prettier-test:
    strategy:
      matrix:
        node: [14, 18, 20]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Copy The Source Dir
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: npm
      - name: Install Dependencies
        run: |
          npm ci
        shell: bash
      - name: Run Prettier Check
        run: |
          prettier ./src --check
      - if: ${{ !cancelled() && success() }}
        run: |
          echo "🎉 ALL RIGHT"
