name: push-workflow
run-name: ${{github.actor}} is pushing to remote main
on:
  push:
    branches: ['master']
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: first-step
          run: |
            echo "First step is running"


